# Generated by Django 5.1.1 on 2026-02-02 11:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password_hash', models.CharField(max_length=256, verbose_name='Хэш пароля')),
                ('first_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, default='', max_length=128, verbose_name='Отчество')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_admin', models.BooleanField(default=False, help_text='Администратор системы может управлять всеми ресурсами и пользователями.', verbose_name='Администратор системы')),
            ],
            options={
                'verbose_name': 'Пользователь системы',
                'verbose_name_plural': 'Пользователи системы',
            },
        ),
    ]
