# Generated by Django 5.1.1 on 2026-02-02 11:54

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('token_jti', models.CharField(max_length=64, unique=True, verbose_name='JTI токена')),
            ],
            options={
                'verbose_name': 'Черный список токенов',
                'verbose_name_plural': 'Черные списки токенов',
            },
        ),
    ]
