# Generated by Django 5.1.1 on 2026-02-02 11:54

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль пользователя',
                'verbose_name_plural': 'Роли пользователей',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('read_permission', models.BooleanField(default=False, verbose_name='Право на чтение')),
                ('read_all_permission', models.BooleanField(default=False, verbose_name='Право на чтение списка всех объектов')),
                ('create_permission', models.BooleanField(default=False, verbose_name='Право на создание')),
                ('update_permission', models.BooleanField(default=False, verbose_name='Право на обновление')),
                ('update_all_permission', models.BooleanField(default=False, verbose_name='Право на обновление всех объектов')),
                ('delete_permission', models.BooleanField(default=False, verbose_name='Право на удаление')),
                ('delete_all_permission', models.BooleanField(default=False, verbose_name='Право на удаление всех объектов')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.resource', verbose_name='Ресурс')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Право доступа роли к ресурсу',
                'verbose_name_plural': 'Права доступа ролей к ресурсам',
                'unique_together': {('role', 'resource')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid6, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='authorization.role', verbose_name='Роль')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь пользователя и роли',
                'verbose_name_plural': 'Связи пользователя и роли',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
